version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mentorlink-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: mentorlink-server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mentorlink
      - PORT=5000
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: mentorlink-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server

volumes:
  mongo_data:
